### ISSUE TITLE
w3c/groups: add and mark community groups

### ISSUE THREAD

**Issue by sidvishnoi** [marcoscaceres/respec.org#100]
Need to add all community groups to [w3c/groups.json](https://github.com/marcoscaceres/respec.org/blob/gh-pages/routes/w3c/groups.json) and also add a distinction between WGs and CGs in API response so it can be used for https://github.com/w3c/respec/issues/3017

**Comment by sidvishnoi** [comment]
There are 330 CGs according to https://www.w3.org/community/groups/, so wish everyone luck in adding shortname->ID mapping :smile:

**Comment by marcoscaceres** [comment]
@sidvishnoi, we probably only need to add the relevant ones (probably just the WICG... most CGs are dead). The W3C is working on adding human readable IDs.

**Comment by marcoscaceres** [comment]
another option is catch it them from the name... they all end with "community group" or "business group" or whatever.

**Comment by sidvishnoi** [comment]
Sending request to https://api.w3.org/groups?items=400&embed=true&apikey=APIKEY, and then processing response as:
```js
Object.fromEntries(
  data._embedded.groups
    .filter((group) => !group._is_closed && group.type === "community group")
    .map((group) => [
      group._links.homepage.href.split("/community/")[1].replace(/\/$/, ""),
      group.id,
    ])
);
```

returned 330 CGs in a format we needed.

Might replace current group fetching logic with above API endpoint to get all groups with needed details at once, instead of sending 360 (or less) HTTP requests! The `embed=true` parameter returns all details we need.

**Comment by marcoscaceres** [comment]
Nice one!
