### ISSUE TITLE
New groups

### ISSUE THREAD

**Issue by xfq** [marcoscaceres/respec.org#105]
Here are some active CGs that might be useful to add to [w3c/groups](https://github.com/marcoscaceres/respec.org/blob/gh-pages/routes/w3c/groups.json):

* [GPU for the Web Community Group](https://www.w3.org/community/gpu/)
* [ACT Rules Community Group](https://www.w3.org/community/act-r/)
* [XForms Users Community Group](https://www.w3.org/community/xformsusers/)
* [MathML Refresh Community Group](https://www.w3.org/community/mathml4/)
* [MiniApps Ecosystem Community Group](https://www.w3.org/community/miniapps/)

We should also figure out the name convention for the WG-CG groups like:

* [Immersive Web WG](https://www.w3.org/immersive-web/) / [Immersive Web CG](https://www.w3.org/community/immersive-web/)
* [WebAssembly WG](https://www.w3.org/wasm/) / [WebAssembly CG](https://www.w3.org/community/webassembly/)
* [Second Screen WG](https://www.w3.org/2014/secondscreen/) / [Second Screen CG](https://www.w3.org/community/webscreens/)

**Comment by xfq** [comment]
Note that GPU is chartering a WG, and EPUB 3 might be a WG in the near future.

**Comment by sidvishnoi** [comment]
Thanks for the list @xfq!

> We should also figure out the name convention for the WG-CG groups like:

We decided to add a `-cg` suffix on such groups, for example, https://github.com/marcoscaceres/respec.org/pull/103/commits/e94b2a851cd352c703fca4220452e961c59eb2a9.

**Comment by marcoscaceres** [comment]
We should check if the groups are using ReSpec or they are likely to produce some kind of report.

**Comment by xfq** [comment]
I don’t know the information of all groups, but for some of the groups I listed above, I know that:

* MiniApp CG uses ReSpec
* MathML refresh CG uses ReSpec

-----

And in the groups currently listed in [w3c/groups](https://github.com/marcoscaceres/respec.org/blob/gh-pages/routes/w3c/groups.json):

* Process CG uses Bikeshed
* CSSWG uses Bikeshed
* GPU CG uses Bikeshed
