### ISSUE TITLE
Use shortname from W3C API

### ISSUE THREAD

**Issue by dontcallmedom** [marcoscaceres/respec.org#114]
To avoid bugs such as the one fixed in #113, it would be best to get the shortname of the groups from the W3C API to populate `routes/w3c/groups.json` - they are now exposed on the /group view (with key .shortname) thanks to @deniak

**Comment by sidvishnoi** [comment]
Is there a chance that the shortnames clash may between WGs and CGs?

**Comment by dontcallmedom** [comment]
yes - more specifically, there are already cases of clashing shortnames between cg/wg

**Comment by sidvishnoi** [comment]
We presently add a `-cg` suffix to clashing names. If we populate `groups.json` using W3C API, there will be inconsistencies. 
ReSpec doesn't expect users to tell us about the group type and only key users need to provide is shortname.

**Comment by dontcallmedom** [comment]
fair enough - maybe this isn't practical. Maybe having a consistency check for wgs would still be useful?

**Comment by sidvishnoi** [comment]
Is this something that can be done on W3C side?

I've only found 5 cases of clash:
```js
['immersive-web', 109735, 'Immersive Web Working Group', 'WG'],
['immersive-web', 87846, 'Immersive Web Community Group', 'CG'],

['json-ld', 107714, 'JSON-LD Working Group', 'WG'],
['json-ld', 49174, 'JSON for Linking Data Community Group', 'CG'],

['timed-text', 34314, 'Timed Text Working Group', 'WG'],
['timed-text', 50119, 'Timed Text Community Group', 'CG'],

['wot', 63991, 'Web of Things Community Group', 'CG'],
['wot', 75874, 'Web of Things Interest Group', 'IG'],
['wot', 95969, 'Web of Things Working Group', 'WG'],

['xpath-next', 98025, 'XPath Next Community Group', 'CG'],
['xproc-next', 101103, 'XProc Next Community Group', 'CG'],
```

Is there a possibility that these group names can be changed?

FWIW, I liked how Publishing group handled this:
```js
['publishing', 100074, 'Publishing Working Group', 'WG'],
['publishingbg', 97159, 'Publishing Business Group', 'BG'],
['publishingcg', 110591, 'Publishing Community Group', 'CG'],
```

**Comment by dontcallmedom** [comment]
My understanding is that it is intentional that different groups may share the same shortname as long as they have different types - in practice, the shortname is used as a slug in various URLs, with the assumption that the group type is also incorporated to avoid overlap.

So I don't think that design constraint to be lifted.

**Comment by sidvishnoi** [comment]
I see. I think we'll have to make the trade-off of requiring users to tell group type here. Maybe we can ask them to provide the type only in case of clashes. WDYT @marcoscaceres?
```
/w3c/groups/webapps     -> no clash, return 
/w3c/groups/wot         -> clash. return 404
/w3c/groups/wot/wg      -> okay
/w3c/groups/webapps/wg  -> for consistency
```

Complicates code a bit, but workable I think.

**Comment by marcoscaceres** [comment]
can we do:
"webapps" | "wot-wg" | "webapps-wg"

The "/" implies a hierarchy.

**Comment by sidvishnoi** [comment]
Some group names already have a `-` suffix, like `"open-ui"`, so I wanted something other than `-cg`. `-` is kinda part of name and not a qualifier.
`/` helps in keep this optional in the API URL.

**Comment by marcoscaceres** [comment]
I could probably live with "/" but as a prefix... that would feel more natural "wg/webapps" for example.

**Comment by sidvishnoi** [comment]
Optional first argument kinda smells bad.
```
/w3c/groups/wg/webapps === /w3c/groups/webapps (backward compatibility and we don't want users to always specify group type) 
/w3c/groups/wot -> ambiguous
/w3c/groups/wg/wot -> okay
```

**Comment by marcoscaceres** [comment]
Right, but we conflating what users provide and how that gets translated into the http request/path. I'm saying that `groups: "wg/whatever"` or even "whatever-wg"  the could become /w3c/groups/webapps/wg in the request.

**Comment by sidvishnoi** [comment]
Ah. I misunderstood. This sounds good to me!
