### ISSUE TITLE
WebRTC WG Patent Policy out of date

### ISSUE THREAD

**Issue by dontcallmedom** [marcoscaceres/respec.org#121]
https://respec.org/w3c/groups/webrtc says the WebRTC WG is under PP2017, but it was switched to PP2020 last Friday. The data returned by the W3C API is uptodate - not sure what needs to be put in motion to update the respec data.

**Comment by sidvishnoi** [comment]
We need to reduce cache duration :smile: 
https://github.com/marcoscaceres/respec.org/blob/4accf80fbff12b5c4097368d910167495cfca0eb/routes/w3c/group.js#L26

Wasn't expecting many updates so kept cache duration long, but there will be enough updates until process policy changes, so will reduce to 3 days. Let me know if you've expectations for quicker updates :slightly_smiling_face:

**Comment by dontcallmedom** [comment]
thanks! Given that we will see a lot of groups transitioning to the patent policy over the upcoming 3 months, I think a one-day cache would probably work best - assuming there is very little cost to updating it on a daily basis

**Comment by sidvishnoi** [comment]
Updated on server :tada:
