### ISSUE TITLE
Hide "advanced options"

### ISSUE THREAD

**Issue by marcoscaceres** [marcoscaceres/respec.org#34]
The following are not very useful in practice: 

![Screenshot 2019-08-01 13 45 27](https://user-images.githubusercontent.com/870154/62264282-a506ed00-b462-11e9-8d18-4b9de2345d56.png)

They are only really useful for debugging purposes. We should hide them under "show advanced search" or something

**Comment by sidvishnoi** [comment]
Closed via https://github.com/marcoscaceres/respec.org/pull/38
