### ISSUE TITLE
Search doesn't work in Safari

### ISSUE THREAD

**Issue by marcoscaceres** [marcoscaceres/respec.org#35]
Throws: 

[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'specs.length')
	getFormData (script.js:91)
	(anonymous function) (script.js:98)
	asyncFunctionResume
	handleSubmit (script.js:97)
	(anonymous function) (script.js:183)

**Comment by sidvishnoi** [comment]
Custom Elements. :shake-my-head:
> [Safari] Supports "Autonomous custom elements" but not "Customized built-in elements".
> https://caniuse.com/#feat=custom-elementsv1

**Comment by sidvishnoi** [comment]
Polyfill? https://github.com/ungap/custom-elements-builtin

**Comment by marcoscaceres** [comment]
Yeah, polyfill.
