### ISSUE TITLE
The standard xref UI cannot search for terms with `.` in them

### ISSUE THREAD

**Issue by janiceshiu** [marcoscaceres/respec.org#60]
`PaymentAddress.postalCode` shows up as a suggestion in xref, thus implying that xref has its its definition. @sidvishnoi confirms that [xref has the correct definition.](https://respec.org/xref/?term=postalCode&for=PaymentAddress)

## Expected:
1. Searching for `PaymentAddress.postalCode` in the `Terms, concept, or WebIDL` field on [xref](https://respec.org/xref/) locates the correct spec and shows the result.

## Actual:
1. Searching for `PaymentAddress.postalCode` in the `Terms, concept, or WebIDL` field on [xref](https://respec.org/xref/) does not locate any specs and shows `No results found.` 
2. To correctly locate the spec, one has to type `postalCode` in the `Terms, concept, or WebIDL` field, `PaymentAddress` in the `for` field and check the `Advanced Search` box. 

## Reason and Suggested Fix
@sidvishnoi confirms that this is because the standard search UI only finds terms without `.`. Ideally, if a term shows up as suggested on xref, one should be able to click it and get the result as normal.

Thank you for helping me debug this, Sid!

**Comment by marcoscaceres** [comment]
This got fixed at some point :)
